version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: db_openbanking
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: openbanking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
volumes:
  mysql-data:
